"""add cascase updatw

Revision ID: 258780cfce09
Revises: fdd45cb454f5
Create Date: 2024-05-12 12:34:03.787952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258780cfce09'
down_revision: Union[str, None] = 'fdd45cb454f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dataset_data_dataset_id_fkey', 'dataset_data', type_='foreignkey')
    op.create_foreign_key(None, 'dataset_data', 'datasets', ['dataset_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('datasets_type_id_fkey', 'datasets', type_='foreignkey')
    op.drop_constraint('datasets_user_id_fkey', 'datasets', type_='foreignkey')
    op.create_foreign_key(None, 'datasets', 'dataset_types', ['type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'datasets', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('evaluation_metrics_metric_id_fkey', 'evaluation_metrics', type_='foreignkey')
    op.drop_constraint('evaluation_metrics_model_id_fkey', 'evaluation_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'evaluation_metrics', 'metrics', ['metric_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluation_metrics', 'model_evaluations', ['model_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('model_evaluations_model_id_fkey', 'model_evaluations', type_='foreignkey')
    op.drop_constraint('model_evaluations_dataset_id_fkey', 'model_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'model_evaluations', 'datasets', ['dataset_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'model_evaluations', 'models', ['model_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('models_type_id_fkey', 'models', type_='foreignkey')
    op.drop_constraint('models_dataset_id_fkey', 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'model_types', ['type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'models', 'datasets', ['dataset_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('train_metrics_model_id_fkey', 'train_metrics', type_='foreignkey')
    op.drop_constraint('train_metrics_metric_id_fkey', 'train_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'train_metrics', 'metrics', ['metric_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'train_metrics', 'models', ['model_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'user_roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'user_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'train_metrics', type_='foreignkey')
    op.drop_constraint(None, 'train_metrics', type_='foreignkey')
    op.create_foreign_key('train_metrics_metric_id_fkey', 'train_metrics', 'metrics', ['metric_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('train_metrics_model_id_fkey', 'train_metrics', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key('models_dataset_id_fkey', 'models', 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('models_type_id_fkey', 'models', 'model_types', ['type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'model_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'model_evaluations', type_='foreignkey')
    op.create_foreign_key('model_evaluations_dataset_id_fkey', 'model_evaluations', 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('model_evaluations_model_id_fkey', 'model_evaluations', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'evaluation_metrics', type_='foreignkey')
    op.drop_constraint(None, 'evaluation_metrics', type_='foreignkey')
    op.create_foreign_key('evaluation_metrics_model_id_fkey', 'evaluation_metrics', 'model_evaluations', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('evaluation_metrics_metric_id_fkey', 'evaluation_metrics', 'metrics', ['metric_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.create_foreign_key('datasets_user_id_fkey', 'datasets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('datasets_type_id_fkey', 'datasets', 'dataset_types', ['type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dataset_data', type_='foreignkey')
    op.create_foreign_key('dataset_data_dataset_id_fkey', 'dataset_data', 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
